project:
  type: website
  output-dir: docs
  render:
    - "index.qmd"
    - "notebooks/*.qmd"

website:
  title: "Single Cell RNA Sequencing Analysis"
  navbar:
    background: primary
    left:
      - text: 0. Home
        href: index.qmd
      - text: 1. Quality Control
        href: notebooks/01.qc.qmd
      - text: 2. Doublet Detection
        href: notebooks/02.doublet_detection.qmd
      - text: 3. Dataset Integration
        href: notebooks/03.integration.qmd
      - text: 4. Annotation
        href: notebooks/04.annotation.qmd
      - text: 5. Pseudobulking and Differential Expression
        href: notebooks/05.pseudo.qmd
      - text: 6. Functional Enrichment Analysis
        href: notebooks/06.fea.qmd
      - text: 7. Subcluster/Subtype Analysis
        href: notebooks/07.subcluster.qmd

about:
  template: solana

format:
  html:
    theme:
      light: [flatly, styles.scss]
      dark: [darkly, styles.scss]
    toc: true
    toc-depth: 2
    code-link: true
    code-fold: true
    code-line-numbers: true
