name: Feature request
description: Suggest additional functionality for this pipeline
title: "[ENH]: "
labels: ["enhancement"]
assignees: []

body:
  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem?
      description: A clear and concise description of what the problem is.
      placeholder: e.g. I'm always frustrated when [...], I need to run [...] analysis
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
      placeholder: e.g. Add support for [...], Clarify what to do at [...] step
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
      placeholder: e.g. I tried X but it didn’t solve the problem.

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any other context about the feature request here.
      placeholder: Links, references, or related issues.

