name: Question template
description: Ask a question about how to use this code base

body:
  - type: textarea
    id: question
    attributes:
      label: Ask your question
    validations:
      required: true
